-- Migracion 00: Tablas fundacionales (documentacion retroactiva)
--
-- Estas tablas fueron creadas antes de que se iniciara el control de migraciones.
-- Este archivo documenta el DDL original para reproducibilidad.
-- NO ejecutar en la base de datos existente (las tablas ya existen).
-- Las columnas numero_aves_total, saldo_aves_total y raza_ave_id en cortes
-- fueron agregadas por migraciones posteriores (22, 29).

-- ============================================================
-- profiles (extiende auth.users con rol)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id         UUID PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
    email      TEXT,
    role       TEXT NOT NULL CHECK (role IN ('administrador', 'operario')),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- fincas (granjas)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.fincas (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     TEXT NOT NULL,
    ubicacion  TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.fincas ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- galpones (galpones de una finca)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.galpones (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finca_id   BIGINT NOT NULL REFERENCES public.fincas (id) ON DELETE RESTRICT,
    nombre     TEXT NOT NULL,
    capacidad  INTEGER,
    saldo_aves INTEGER NOT NULL DEFAULT 0 CHECK (saldo_aves >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.galpones ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- cortes (lotes de produccion)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.cortes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio     TIMESTAMPTZ NOT NULL,
    fecha_final      TIMESTAMPTZ,
    notas            TEXT,
    estado           TEXT NOT NULL DEFAULT 'activo',
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cortes ENABLE ROW LEVEL SECURITY;
