-- Eliminar la tabla productos existente (si existe) para recrearla con el nuevo esquema
DROP TABLE IF EXISTS public.productos;

-- SQL para crear la tabla 'productos' con el campo 'codigo' como entero autoincremental
-- y 'unidad_medida_codigo' como clave foránea a 'unidades_medida.codigo'
CREATE TABLE public.productos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 10) UNIQUE,
    descripcion TEXT,
    unidad_medida_codigo TEXT NOT NULL REFERENCES public.unidades_medida(codigo)
);
