-- db_migrations/13_create_registro_mortalidad_table.sql

CREATE TABLE public.registro_mortalidad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    galpon_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    numero_secuencia INTEGER NOT NULL,
    causa_mortalidad_codigo TEXT NOT NULL,
    cantidad_aves_muertas INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    -- Restricción para asegurar la unicidad de los registros de mortalidad por galpón, fecha y secuencia
    UNIQUE (galpon_id, fecha, numero_secuencia),

    -- Clave foránea al galpón
    FOREIGN KEY (galpon_id) REFERENCES public.galpones(id) ON DELETE CASCADE,

    -- Clave foránea a la causa de mortalidad
    FOREIGN KEY (causa_mortalidad_codigo) REFERENCES public.causas_mortalidad(codigo) ON DELETE RESTRICT,

    -- Clave foránea al registro diario del galpón
    -- Esto asegura que solo se puedan registrar mortalidades para días y galpones con un registro diario existente
    FOREIGN KEY (galpon_id, fecha) REFERENCES public.registro_diario_galpon(galpon_id, fecha) ON DELETE CASCADE
);

-- Habilitar RLS en la tabla registro_mortalidad
ALTER TABLE public.registro_mortalidad ENABLE ROW LEVEL SECURITY;

-- Política de RLS para administradores: pueden gestionar toda la mortalidad
CREATE POLICY "Los administradores pueden gestionar toda la mortalidad" ON public.registro_mortalidad
  FOR ALL USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'administrador'));

-- Política de RLS para operarios: pueden gestionar la mortalidad de sus galpones asignados
CREATE POLICY "Los operarios pueden gestionar la mortalidad de sus galpones" ON public.registro_mortalidad
  FOR ALL USING (EXISTS (
    SELECT 1 FROM public.operario_galpones og
    WHERE og.galpon_id = registro_mortalidad.galpon_id AND og.operario_id = auth.uid()
  ));
