-- db_migrations/17_create_alimentos_catalog.sql
-- Catalogo de alimentos por fabricante para desacoplar alimentacion de la tabla productos.
-- Incluye categoria, backfill legado y sincronizacion de la secuencia de codigo.

BEGIN;

-- 1) Fabricantes de alimento
CREATE TABLE IF NOT EXISTS public.fabricantes_alimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2) Alimentos
CREATE TABLE IF NOT EXISTS public.alimentos (
    codigo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fabricante_alimento_id BIGINT NOT NULL REFERENCES public.fabricantes_alimento(id) ON DELETE RESTRICT,
    descripcion TEXT NOT NULL,
    categoria TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (fabricante_alimento_id, descripcion)
);

-- Si la tabla ya existia sin categoria, la agrega.
ALTER TABLE public.alimentos
  ADD COLUMN IF NOT EXISTS categoria TEXT;

-- Constraint de categorias validas (solo si no existe).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'alimentos_categoria_check'
      AND conrelid = 'public.alimentos'::regclass
  ) THEN
    ALTER TABLE public.alimentos
      ADD CONSTRAINT alimentos_categoria_check
      CHECK (
        categoria IS NULL OR
        categoria IN (
          'levante',
          'prepostura',
          'postura',
          'pico',
          'mantenimiento',
          'retiro',
          'concentrado',
          'aditivo',
          'materia_prima'
        )
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_alimentos_fabricante
    ON public.alimentos (fabricante_alimento_id);

CREATE INDEX IF NOT EXISTS idx_alimentos_categoria
    ON public.alimentos (categoria);

-- 3) RLS
ALTER TABLE public.fabricantes_alimento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alimentos ENABLE ROW LEVEL SECURITY;

-- Lectura para cualquier usuario autenticado
DROP POLICY IF EXISTS "Usuarios autenticados pueden ver fabricantes de alimento" ON public.fabricantes_alimento;
CREATE POLICY "Usuarios autenticados pueden ver fabricantes de alimento"
  ON public.fabricantes_alimento FOR SELECT
  USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Usuarios autenticados pueden ver alimentos" ON public.alimentos;
CREATE POLICY "Usuarios autenticados pueden ver alimentos"
  ON public.alimentos FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Gestion solo para administradores (usa funcion SECURITY DEFINER existente)
DROP POLICY IF EXISTS "Los administradores pueden gestionar fabricantes de alimento" ON public.fabricantes_alimento;
CREATE POLICY "Los administradores pueden gestionar fabricantes de alimento"
  ON public.fabricantes_alimento FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Los administradores pueden gestionar alimentos" ON public.alimentos;
CREATE POLICY "Los administradores pueden gestionar alimentos"
  ON public.alimentos FOR ALL
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- 4) Backfill de codigos de alimento usados historicamente para no romper la FK.
DO $$
DECLARE
  v_fabricante_legado_id BIGINT;
BEGIN
  INSERT INTO public.fabricantes_alimento (nombre)
  VALUES ('LEGADO')
  ON CONFLICT (nombre) DO NOTHING;

  SELECT id
  INTO v_fabricante_legado_id
  FROM public.fabricantes_alimento
  WHERE nombre = 'LEGADO';

  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'registro_diario_galpon'
  ) THEN
    INSERT INTO public.alimentos (codigo, fabricante_alimento_id, descripcion, categoria, activo)
    SELECT
      rdg.producto_alimento_codigo,
      v_fabricante_legado_id,
      COALESCE(p.descripcion, 'Alimento legado codigo ' || rdg.producto_alimento_codigo::TEXT),
      'postura',
      TRUE
    FROM (
      SELECT DISTINCT producto_alimento_codigo
      FROM public.registro_diario_galpon
      WHERE producto_alimento_codigo IS NOT NULL
    ) rdg
    LEFT JOIN public.productos p
      ON p.codigo = rdg.producto_alimento_codigo
    ON CONFLICT (codigo) DO NOTHING;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'registro_alimentacion_galpon'
  ) THEN
    INSERT INTO public.alimentos (codigo, fabricante_alimento_id, descripcion, categoria, activo)
    SELECT
      rag.producto_alimento_codigo,
      v_fabricante_legado_id,
      COALESCE(p.descripcion, 'Alimento legado codigo ' || rag.producto_alimento_codigo::TEXT),
      'postura',
      TRUE
    FROM (
      SELECT DISTINCT producto_alimento_codigo
      FROM public.registro_alimentacion_galpon
      WHERE producto_alimento_codigo IS NOT NULL
    ) rag
    LEFT JOIN public.productos p
      ON p.codigo = rag.producto_alimento_codigo
    ON CONFLICT (codigo) DO NOTHING;
  END IF;
END
$$;

-- 5) Reapuntar FK de registro de alimentacion al nuevo catalogo de alimentos.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'registro_diario_galpon'
  ) THEN
    ALTER TABLE public.registro_diario_galpon
      DROP CONSTRAINT IF EXISTS registro_diario_galpon_producto_alimento_codigo_fkey;

    ALTER TABLE public.registro_diario_galpon
      ADD CONSTRAINT registro_diario_galpon_producto_alimento_codigo_fkey
      FOREIGN KEY (producto_alimento_codigo)
      REFERENCES public.alimentos(codigo);
  END IF;

  IF EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'registro_alimentacion_galpon'
  ) THEN
    -- Eliminar ambos nombres posibles de constraint (antes y despues del rename de la tabla)
    ALTER TABLE public.registro_alimentacion_galpon
      DROP CONSTRAINT IF EXISTS registro_diario_galpon_producto_alimento_codigo_fkey;
    ALTER TABLE public.registro_alimentacion_galpon
      DROP CONSTRAINT IF EXISTS registro_alimentacion_galpon_producto_alimento_codigo_fkey;

    ALTER TABLE public.registro_alimentacion_galpon
      ADD CONSTRAINT registro_alimentacion_galpon_producto_alimento_codigo_fkey
      FOREIGN KEY (producto_alimento_codigo)
      REFERENCES public.alimentos(codigo);
  END IF;
END
$$;

-- 6) Sincronizar sequence/identity de alimentos.codigo.
DO $$
DECLARE
  v_next BIGINT;
BEGIN
  SELECT COALESCE(MAX(codigo), 0) + 1
  INTO v_next
  FROM public.alimentos;

  PERFORM setval(
    pg_get_serial_sequence('public.alimentos', 'codigo'),
    v_next,
    false
  );
END
$$;

COMMIT;
